try:
   
   pass

except ValueError:
 
   pass

except (TypeError, ZeroDivisionError):
   # handle multiple exceptions
 
   pass

except:
   
   pass
